comments/urls.py
from django.urls import path
from comments import views

app_name = "comments"

urlpatterns = [
    path('reg/',views.comment_register, name = "register_comment"),
    path('update-like/',views.update_like, name = "likes"),
    path('delete/',views.delete_comment, name = "delete_comment"),
]

main/urls.py
from django.urls import path
from main import views

app_name = "main"

urlpatterns = [
    path('',views.get_profile, name = "main"),
]

users/urls.py
from django.urls import path
from main import views as main_views
from users import views as users_views


app_name = "users"

urlpatterns = [
    path('register/',users_views.register, name = 'register'),
    path('login/', users_views.user_login, name = 'login'),
    path('logout/',users_views.user_logout, name = "logout"),
    path('save-color/',users_views.save_color, name = "save-color"),
]

visit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('comments/', include('comments.urls', namespace='comments')),
]

comments/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

from users.models import CustomUser
# Create your models here.
# from users.models import CustomUser

class Comments(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.PROTECT)
    date = models.DateTimeField(default=timezone.now)
    likes = models.DecimalField(max_digits=100, decimal_places=0, default=0)
    value = models.CharField(null=True)


class Like(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)  # кто поставил лайк
    comment = models.ForeignKey(Comments, on_delete=models.CASCADE)  # на какой комментарий поставлен лайк
    date = models.DateTimeField(default=timezone.now)  # когда был поставлен лайк

main/models.py
from ast import mod
from django.db import models

# from users.models import User

# Create your models here.

users/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    
    color_theme = models.CharField(max_length=50)

users/forms.py
# users/forms.py

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from django.contrib.auth.models import User

from users.models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField()
    email = forms.EmailField()
    password1 = forms.CharField() 
    password2 = forms.CharField() 
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1','password2']

class CustomUserAuthForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password']

comments/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
# Create your views here.
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from comments.models import Comments, Like
from django.contrib.auth.models import User





def comment_register(request):
    if request.method == "POST" and request.user.is_authenticated:
        comment_text = request.POST.get("comment")
        Comments.objects.create(user=request.user, value=comment_text, likes=0)   
        return redirect('main:main')

    return redirect('main:main')

def delete_comment(request):
    if request.method == "POST" and request.user.is_authenticated:
        Comments.objects.get(id = request.POST.get("comment-id")).delete()
        return redirect('main:main')
    return redirect('main:main')


def update_like(request):
    if request.method == 'POST' and request.user.is_authenticated:
        try:
            like_action = int(request.POST.get('likeAction'))
        except ValueError:
            return JsonResponse({'success': False, 'message': 'Invalid action'}, status=400)
        comment = Comments.objects.get(id = request.POST.get('comment'))

        Like_exist = Like.objects.filter(user = request.user, comment = comment).exists()
        if like_action == 1:
            if not Like_exist:
                comment.likes += 1 
                Like.objects.create(user = request.user, comment = comment)
                print("Лайк добавлен")
            else: 
                return redirect("main:main")
            
        elif like_action == 0:

            if Like_exist:
                comment.likes -= 1
                Like.objects.get(user = request.user, comment = comment).delete()
                print("Лайк удален")
            else:
                return redirect("main:main")
        else:
            return JsonResponse({'success': False, 'message': 'Invalid action'}, status=400)
        comment.save()
        return JsonResponse({'success': True})
    
    return JsonResponse({'success': False, 'message': 'Invalid request method'}, status=400)

main/views.py
from django.shortcuts import render
from django.http import JsonResponse

from comments.models import Comments, Like

# Create your views here.


def get_profile(request):
    errors = request.session.get('form_errors',None)

    if errors:
        del request.session['form_errors']

    if request.user.is_authenticated:
        liked_comments = Like.objects.filter(user = request.user).values_list('comment_id', flat=True)
        color = request.user.color_theme
    else:
        liked_comments = []
        color = "rgba(0, 191, 255, 1)"
    context = {
        "comments" : Comments.objects.all().order_by("-id"),
        "liked_comments" : liked_comments,
        "errors": errors,
        "color":color
    }
    
        
    return render(request, "visit.html", context=context)

users/views.py
from django.contrib.auth import login, authenticate, logout
import json
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.shortcuts import render,redirect

from comments.models import Comments
from users.forms import CustomUserCreationForm, CustomUserAuthForm
from django.http import JsonResponse

from users.models import CustomUser

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)

        if form.is_valid():
            user = form.save()
            return redirect('main:main')

        else:
            errors = {}
            for field, error_list in form.errors.items():
                errors[field] = error_list
            request.session['form_errors'] = errors
            return  redirect('main:main')
    return redirect('main:main')

def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            
            user = authenticate(request, username=username, password=password)
            
            if user is not None:
                login(request, user)

                return redirect('main:main')
        else:
            errors = {}
            for field, error_list in form.errors.items():
                errors[field] = error_list
            request.session['form_errors'] = errors
            return  redirect('main:main')
    
    return redirect('main:main')

def user_logout(request):
    if request.method == "POST" and request.user.is_authenticated:
        logout(request)
    return redirect("main:main")

def save_color(request):
    if request.method == "POST" and request.user.is_authenticated:
        data = json.loads(request.body)
        get_color = data.get('color')
        user = request.user
        user.color_theme = get_color
        user.save()
        print(get_color)
    
    return redirect("main:main")
        

templates/visit.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token }}">
    <title>Визитка</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&display=swap" rel="stylesheet">
    <link rel="icon" href="{% static "images/favfav.png" %}" type="image/x-icon">
    <script>
        var saveColorUrl = "{% url 'users:save-color' %}";  // Рендерим URL в переменную JavaScript
        // Получаем значение цвета из Django переменной
        var colorDesign = "{{ color }}";
        
         // Устанавливаем его в качестве переменной CSS
         document.documentElement.style.setProperty('--color-design', colorDesign);
    </script> 
</head>


<body>
    <div class="container" style="position: relative;">
            <!-- Круглая кнопка-меню -->
        <div class="auth-container">
            <div class="auth-icon" onclick="toggleAuthMenu()"></div>
            <div class="auth-menu">
                {% if user.is_authenticated %}
                <div class="user-info">
                    <p class="auth-name-icon">{{ user.username }}</p>
                    <form action="{% url 'users:logout' %}" method="post" class="logout-form">
                        {% csrf_token %}
                        <button>Выйти</button>
                    </form>
                </div>
                {% else %}
            
                <button onclick="openModal('loginModal')">Войти</button>
                <button onclick="openModal('registerModal')">Регистрация</button>
                {% endif %}
                <!-- Палитра цветов -->
                <button class="open-modal-btn" onclick="openModal('colorModal')">Выбрать цвет</button>
            </div>
        </div>
            <!-- Модальное окно -->
        <div id="colorModal" class="modal">
            <div id = "modal-palitre" class="modal-content">
                <span class="close" onclick="closeModal('colorModal')">&times;</span>
                <h2>Выберите цвет</h2>
                
                <!-- Палитра цветов -->
                <div class="controls">
                    <input type="color" id="colorPicker1" value="#ff0000">
                    <input type="range" id="alphaSlider" min="0" max="1" step="0.01" value="1">
                </div>
                <button onclick="closeModal('colorModal'); submitColor() ">Сохранить</button>
            </div>
        </div>
    

        <img src="{% static "images/photo_profile.jpg" %}" alt="Фото профиля" class="profile-img">
        <h1>netkaruma</h1>
        <p>Даня, 22 года</p>
        <p>Стэк: Backend django,python,postgresql,doker</p>
        <p>Стэк: Frontend JavaScript ajax,html,css</p>
        
        <!-- Кнопки для открытия модального окна -->
    
        <!-- Модальное окно авторизации -->
    <div id="loginModal" class="modal">
        <div class="modal-content">
            <span class="close" onclick="closeModal('loginModal')">&times;</span>
            <h2>Вход</h2>
            <form id="loginForm" action="{% url 'users:login' %}" method="POST">
                {% csrf_token %}
                <input name = "username" type="text" placeholder="Логин">
                <input name = "password" type="password" placeholder="Пароль">
                <button onclick="submit">Войти</button>
                <button type="button" onclick="closeModal('loginModal'); openModal('registerModal')">Регистрация</button>
            </form>
        </div>
    </div>
    <!-- Модальное окно регистрации -->
    <div id="registerModal" class="modal">
        <div class="modal-content">
            <span class="close" onclick="closeModal('registerModal')">&times;</span>
            <h2>Регистрация</h2>
            <form id="registerForm" action="{% url 'users:register' %}" method="POST">
                {% csrf_token %}
                <input name="username" type="text" placeholder="Логин" required>
                <input name="email" type="email" placeholder="Email" required>
                <input name="password1" type="password" placeholder="Пароль" required>
                <input name="password2" type="password" placeholder="Пароль" required>
                <button type="submit">Зарегистрироваться</button>
                <button type="button" onclick="closeModal('registerModal'); openModal('loginModal')">Авторизация</button>
            </form>
        </div>
    </div>

    <div class="social-links">
        <a href="https://github.com/netkaruma" target="_blank" class="social-button">GitHub</a>
        <a href="https://vk.com/danilmanzurov" target="_blank" class="social-button">Vk</a>
        <a href="mailto:dani.manz@mail.ru" target="_blank" class="social-button">Email</a>
        {# <a href="https://shikimori.one/dvedalus" target="_blank" class="social-button">Shikimori</a> #}
    </div>
    

    {% if errors %}
    <div id="notifications" class="notification">
        <div class="header">
            <span class="title">Ошибка</span>
            <span class="close" onclick="closeNotification()">×</span>
        </div>
        <div class="content">
            {% for key,texts in errors.items %}
                {% for error in texts %}
                {{error}}
                {% endfor %}
            {% endfor %}
        </div>
    </div>
    {% endif %}
    

    <div class="comment-section">
        <h2>Оставьте комментарий</h2>
        <form action = "{% url "comments:register_comment" %}" method = "post">
            {% csrf_token %}
            <textarea id="commentInput" name="comment" placeholder="Введите ваш комментарий..." required></textarea><br>
            <button class="submit-button" type="submit">Отправить</button>
        </form>

        <!-- Пример комментариев с лайками -->
        {% for element in comments %}
        <div class="user-comment" comment-id = "{{element.id}}">
            <strong>{{ element.user.username }}</strong>
            <p>{{ element.value }}</p>
            <small>{{ element.date|timesince }} назад</small> <!-- Показывает время с момента публикации -->
            {% if element.user == user %}
            <form method="post" action = "{% url "comments:delete_comment" %}">
                {% csrf_token %}
                <input type="hidden" name="comment-id" value="{{element.id}}">
                <button class="delete-comment">✖</button>
            </form>
                {% endif %}
            <div class="like-container">
                <span class="like-count">{{ element.likes }}</span>
                <button class="like-button {% if element.id in liked_comments %}liked{% endif %}">❤️</button>
            </div>
        </div>
        {% endfor %}
            
        </div>
    </div>
    
    <script src = "{% static "js/scripts.js" %}"></script>
</body>
</html>